server:
  port: 8080

spring:
  datasource:
    username: root
    password: Ming@Yin8023
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.172.206:3306/my_account?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
